# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/pyarchinit/.qgis/python/plugins/pyarchinit/modules/gui/pyarchinit_US_ui.ui'
#
# Created: Thu Mar  4 22:50:52 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(607, 789)
        Dialog.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/iconPAI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_18 = QtGui.QGridLayout(Dialog)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(-1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_29 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.pushButton_connect = QtGui.QPushButton(Dialog)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout_2.addWidget(self.pushButton_connect, 0, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_first_rec = QtGui.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/5_leftArrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon1)
        self.pushButton_first_rec.setObjectName("pushButton_first_rec")
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 0, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(Dialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/4_leftArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon2)
        self.pushButton_prev_rec.setObjectName("pushButton_prev_rec")
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 1, 1, 2)
        self.pushButton_next_rec = QtGui.QPushButton(Dialog)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/6_rightArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon3)
        self.pushButton_next_rec.setObjectName("pushButton_next_rec")
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 4, 1, 1)
        self.pushButton_last_rec = QtGui.QPushButton(Dialog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/7_rightArrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon4)
        self.pushButton_last_rec.setObjectName("pushButton_last_rec")
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 5, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/newrec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon5)
        self.pushButton_new_rec.setObjectName("pushButton_new_rec")
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 6, 1, 1)
        self.pushButton_save = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/b_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon6)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 0, 7, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon7)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(70, 30, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/new_search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon8)
        self.pushButton_new_search.setObjectName("pushButton_new_search")
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 4, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon9)
        self.pushButton_search_go.setObjectName("pushButton_search_go")
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 5, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/sort.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon10)
        self.pushButton_sort.setObjectName("pushButton_sort")
        self.gridLayout.addWidget(self.pushButton_sort, 1, 6, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/view_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon11)
        self.pushButton_view_all.setObjectName("pushButton_view_all")
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 7, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line_6 = QtGui.QFrame(Dialog)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_42 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_43 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_43.setFont(font)
        self.label_43.setMargin(0)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(Dialog)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName("label_status")
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName("label_sort")
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setMargin(0)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_27 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setMargin(0)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName("label_rec_corrente")
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setMargin(0)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_rec_tot = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName("label_rec_tot")
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_8 = QtGui.QFrame(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_sito = QtGui.QComboBox(Dialog)
        self.comboBox_sito.setEnabled(False)
        self.comboBox_sito.setMinimumSize(QtCore.QSize(341, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sito.setFont(font)
        self.comboBox_sito.setMouseTracking(True)
        self.comboBox_sito.setEditable(True)
        self.comboBox_sito.setMaxVisibleItems(99999)
        self.comboBox_sito.setMaxCount(2147483647)
        self.comboBox_sito.setObjectName("comboBox_sito")
        self.comboBox_sito.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_sito)
        self.comboBox_area = QtGui.QComboBox(Dialog)
        self.comboBox_area.setEnabled(False)
        self.comboBox_area.setMaximumSize(QtCore.QSize(64, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_area.setFont(font)
        self.comboBox_area.setEditable(True)
        self.comboBox_area.setObjectName("comboBox_area")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_area)
        self.lineEdit_us = QtGui.QLineEdit(Dialog)
        self.lineEdit_us.setEnabled(False)
        self.lineEdit_us.setMinimumSize(QtCore.QSize(61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lineEdit_us.setFont(font)
        self.lineEdit_us.setObjectName("lineEdit_us")
        self.horizontalLayout_2.addWidget(self.lineEdit_us)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem2 = QtGui.QSpacerItem(303, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem3 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem4 = QtGui.QSpacerItem(97, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox_def_strat = QtGui.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_def_strat.setFont(font)
        self.comboBox_def_strat.setEditable(True)
        self.comboBox_def_strat.setObjectName("comboBox_def_strat")
        self.comboBox_def_strat.addItem("")
        self.comboBox_def_strat.addItem("")
        self.comboBox_def_strat.addItem("")
        self.comboBox_def_strat.addItem("")
        self.comboBox_def_strat.addItem("")
        self.comboBox_def_strat.addItem("")
        self.comboBox_def_strat.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_def_strat, 0, 0, 1, 1)
        self.comboBox_def_intepret = QtGui.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_def_intepret.setFont(font)
        self.comboBox_def_intepret.setEditable(True)
        self.comboBox_def_intepret.setObjectName("comboBox_def_intepret")
        self.comboBox_def_intepret.addItem("")
        self.comboBox_def_intepret.addItem("")
        self.comboBox_def_intepret.addItem("")
        self.comboBox_def_intepret.addItem("")
        self.comboBox_def_intepret.addItem("")
        self.comboBox_def_intepret.addItem("")
        self.comboBox_def_intepret.addItem("")
        self.comboBox_def_intepret.addItem("")
        self.comboBox_def_intepret.addItem("")
        self.comboBox_def_intepret.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_def_intepret, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.verticalLayout_15.addLayout(self.verticalLayout_4)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_17 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_12 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_15.addWidget(self.label_12, 0, 0, 1, 4)
        self.label_37 = QtGui.QLabel(self.tab_2)
        self.label_37.setMinimumSize(QtCore.QSize(0, 15))
        self.label_37.setObjectName("label_37")
        self.gridLayout_15.addWidget(self.label_37, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setMinimumSize(QtCore.QSize(0, 15))
        self.label_14.setObjectName("label_14")
        self.gridLayout_15.addWidget(self.label_14, 1, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setMinimumSize(QtCore.QSize(0, 15))
        self.label_18.setObjectName("label_18")
        self.gridLayout_15.addWidget(self.label_18, 1, 5, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setMinimumSize(QtCore.QSize(0, 15))
        self.label_22.setObjectName("label_22")
        self.gridLayout_15.addWidget(self.label_22, 1, 6, 1, 1)
        self.comboBox_per_iniz = QtGui.QComboBox(self.tab_2)
        self.comboBox_per_iniz.setObjectName("comboBox_per_iniz")
        self.comboBox_per_iniz.addItem("")
        self.comboBox_per_iniz.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_per_iniz, 3, 0, 1, 1)
        self.lineEdit_attivita = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_attivita.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_attivita.setFont(font)
        self.lineEdit_attivita.setObjectName("lineEdit_attivita")
        self.gridLayout_15.addWidget(self.lineEdit_attivita, 3, 5, 1, 1)
        self.lineEdit_struttura = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_struttura.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_struttura.setFont(font)
        self.lineEdit_struttura.setObjectName("lineEdit_struttura")
        self.gridLayout_15.addWidget(self.lineEdit_struttura, 3, 6, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_15.addWidget(self.label_24, 4, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_15.addWidget(self.label_10, 4, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_15.addWidget(self.label_32, 4, 4, 1, 1)
        self.comboBox_fas_iniz = QtGui.QComboBox(self.tab_2)
        self.comboBox_fas_iniz.setObjectName("comboBox_fas_iniz")
        self.gridLayout_15.addWidget(self.comboBox_fas_iniz, 3, 1, 1, 1)
        self.comboBox_per_fin = QtGui.QComboBox(self.tab_2)
        self.comboBox_per_fin.setObjectName("comboBox_per_fin")
        self.gridLayout_15.addWidget(self.comboBox_per_fin, 3, 3, 1, 1)
        self.comboBox_fas_fin = QtGui.QComboBox(self.tab_2)
        self.comboBox_fas_fin.setObjectName("comboBox_fas_fin")
        self.gridLayout_15.addWidget(self.comboBox_fas_fin, 3, 4, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_15)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_8.addWidget(self.line_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.lineEdit_anno = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_anno.setObjectName("lineEdit_anno")
        self.gridLayout_16.addWidget(self.lineEdit_anno, 0, 2, 1, 1)
        self.comboBox_metodo = QtGui.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_metodo.setFont(font)
        self.comboBox_metodo.setEditable(True)
        self.comboBox_metodo.setObjectName("comboBox_metodo")
        self.comboBox_metodo.addItem("")
        self.comboBox_metodo.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_metodo, 0, 4, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_16.addWidget(self.label_33, 1, 4, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_16.addWidget(self.label_17, 1, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem5, 0, 3, 1, 1)
        self.comboBox_scavato = QtGui.QComboBox(self.tab_2)
        self.comboBox_scavato.setEditable(True)
        self.comboBox_scavato.setObjectName("comboBox_scavato")
        self.comboBox_scavato.addItem("")
        self.comboBox_scavato.addItem("")
        self.comboBox_scavato.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_scavato, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_16.addWidget(self.label_8, 1, 0, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_16)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_10.addWidget(self.line_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.pushButton_insert_row_rapporti = QtGui.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_rapporti.setFont(font)
        self.pushButton_insert_row_rapporti.setObjectName("pushButton_insert_row_rapporti")
        self.horizontalLayout_4.addWidget(self.pushButton_insert_row_rapporti)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.verticalLayout_14.addLayout(self.verticalLayout_11)
        self.tableWidget_rapporti = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_rapporti.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_rapporti.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_rapporti.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_rapporti.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_rapporti.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_rapporti.setRowCount(1)
        self.tableWidget_rapporti.setColumnCount(2)
        self.tableWidget_rapporti.setObjectName("tableWidget_rapporti")
        self.tableWidget_rapporti.setColumnCount(2)
        self.tableWidget_rapporti.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_rapporti.setHorizontalHeaderItem(1, item)
        self.verticalLayout_14.addWidget(self.tableWidget_rapporti)
        self.gridLayout_17.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.textEdit_descrizione = QtGui.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione.setFont(font)
        self.textEdit_descrizione.setObjectName("textEdit_descrizione")
        self.verticalLayout_5.addWidget(self.textEdit_descrizione)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.textEdit_interpretazione = QtGui.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_interpretazione.setFont(font)
        self.textEdit_interpretazione.setObjectName("textEdit_interpretazione")
        self.verticalLayout_5.addWidget(self.textEdit_interpretazione)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.gridLayout_7.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.comboBox_formazione = QtGui.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_formazione.setFont(font)
        self.comboBox_formazione.setEditable(True)
        self.comboBox_formazione.setObjectName("comboBox_formazione")
        self.comboBox_formazione.addItem("")
        self.comboBox_formazione.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_formazione, 0, 0, 1, 1)
        self.tableWidget_inclusi = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_inclusi.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_inclusi.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_inclusi.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_inclusi.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_inclusi.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_inclusi.setRowCount(1)
        self.tableWidget_inclusi.setColumnCount(1)
        self.tableWidget_inclusi.setObjectName("tableWidget_inclusi")
        self.tableWidget_inclusi.setColumnCount(1)
        self.tableWidget_inclusi.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_inclusi.setHorizontalHeaderItem(0, item)
        self.gridLayout_10.addWidget(self.tableWidget_inclusi, 0, 1, 6, 1)
        self.tableWidget_campioni = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_campioni.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_campioni.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_campioni.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_campioni.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_campioni.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_campioni.setRowCount(1)
        self.tableWidget_campioni.setColumnCount(1)
        self.tableWidget_campioni.setObjectName("tableWidget_campioni")
        self.tableWidget_campioni.setColumnCount(1)
        self.tableWidget_campioni.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_campioni.setHorizontalHeaderItem(0, item)
        self.gridLayout_10.addWidget(self.tableWidget_campioni, 0, 2, 6, 1)
        self.label_20 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_10.addWidget(self.label_20, 1, 0, 1, 1)
        self.comboBox_colore = QtGui.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_colore.setFont(font)
        self.comboBox_colore.setEditable(True)
        self.comboBox_colore.setObjectName("comboBox_colore")
        self.comboBox_colore.addItem("")
        self.comboBox_colore.addItem("")
        self.comboBox_colore.addItem("")
        self.comboBox_colore.addItem("")
        self.comboBox_colore.addItem("")
        self.comboBox_colore.addItem("")
        self.comboBox_colore.addItem("")
        self.comboBox_colore.addItem("")
        self.comboBox_colore.addItem("")
        self.comboBox_colore.setItemText(8, "")
        self.comboBox_colore.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_colore, 2, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_10.addWidget(self.label_21, 3, 0, 1, 1)
        self.comboBox_consistenza = QtGui.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_consistenza.setFont(font)
        self.comboBox_consistenza.setEditable(True)
        self.comboBox_consistenza.setObjectName("comboBox_consistenza")
        self.comboBox_consistenza.addItem("")
        self.comboBox_consistenza.addItem("")
        self.comboBox_consistenza.addItem("")
        self.comboBox_consistenza.addItem("")
        self.comboBox_consistenza.addItem("")
        self.comboBox_consistenza.addItem("")
        self.comboBox_consistenza.setItemText(5, "")
        self.comboBox_consistenza.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_consistenza, 4, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 5, 0, 1, 1)
        self.comboBox_conservazione = QtGui.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_conservazione.setFont(font)
        self.comboBox_conservazione.setEditable(True)
        self.comboBox_conservazione.setObjectName("comboBox_conservazione")
        self.comboBox_conservazione.addItem("")
        self.comboBox_conservazione.addItem("")
        self.comboBox_conservazione.addItem("")
        self.comboBox_conservazione.addItem("")
        self.comboBox_conservazione.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_conservazione, 6, 0, 1, 1)
        self.pushButton_insert_row_inclusi = QtGui.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_inclusi.setFont(font)
        self.pushButton_insert_row_inclusi.setObjectName("pushButton_insert_row_inclusi")
        self.gridLayout_10.addWidget(self.pushButton_insert_row_inclusi, 6, 1, 1, 1)
        self.pushButton_insert_row_campioni = QtGui.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_campioni.setFont(font)
        self.pushButton_insert_row_campioni.setObjectName("pushButton_insert_row_campioni")
        self.gridLayout_10.addWidget(self.pushButton_insert_row_campioni, 6, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 7, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_10)
        self.line_4 = QtGui.QFrame(self.tab_3)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_6.addWidget(self.line_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.comboBox_schedatore = QtGui.QComboBox(self.tab_3)
        self.comboBox_schedatore.setEditable(True)
        self.comboBox_schedatore.setObjectName("comboBox_schedatore")
        self.comboBox_schedatore.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_schedatore, 0, 0, 1, 2)
        self.label_35 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_11.addWidget(self.label_35, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(248, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem6, 1, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lineEdit_data_schedatura = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_data_schedatura.setObjectName("lineEdit_data_schedatura")
        self.gridLayout_12.addWidget(self.lineEdit_data_schedatura, 0, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_12.addWidget(self.label_25, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_13)
        self.gridLayout_14.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_38 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_9.addWidget(self.label_38, 1, 0, 1, 1)
        self.toolButtonGis = QtGui.QToolButton(self.tab_4)
        self.toolButtonGis.setMinimumSize(QtCore.QSize(109, 0))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/GIS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGis.setIcon(icon12)
        self.toolButtonGis.setCheckable(True)
        self.toolButtonGis.setChecked(False)
        self.toolButtonGis.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonGis.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonGis.setObjectName("toolButtonGis")
        self.gridLayout_9.addWidget(self.toolButtonGis, 1, 1, 1, 2)
        self.label_39 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_9.addWidget(self.label_39, 2, 0, 1, 1)
        self.toolButtonPreview = QtGui.QToolButton(self.tab_4)
        self.toolButtonPreview.setIcon(icon12)
        self.toolButtonPreview.setCheckable(True)
        self.toolButtonPreview.setChecked(False)
        self.toolButtonPreview.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPreview.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPreview.setObjectName("toolButtonPreview")
        self.gridLayout_9.addWidget(self.toolButtonPreview, 2, 1, 1, 2)
        self.label_40 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_9.addWidget(self.label_40, 4, 0, 1, 1)
        self.pushButton_showSelectedFeatures = QtGui.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_showSelectedFeatures.setFont(font)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/sheet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_showSelectedFeatures.setIcon(icon13)
        self.pushButton_showSelectedFeatures.setObjectName("pushButton_showSelectedFeatures")
        self.gridLayout_9.addWidget(self.pushButton_showSelectedFeatures, 4, 2, 1, 2)
        self.label_41 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_9.addWidget(self.label_41, 5, 0, 1, 2)
        self.pushButton_pdf_exp = QtGui.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_pdf_exp.setFont(font)
        self.pushButton_pdf_exp.setIcon(icon13)
        self.pushButton_pdf_exp.setObjectName("pushButton_pdf_exp")
        self.gridLayout_9.addWidget(self.pushButton_pdf_exp, 5, 2, 1, 2)
        self.label_36 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_9.addWidget(self.label_36, 0, 0, 1, 1)
        self.toolButtonPan = QtGui.QToolButton(self.tab_4)
        self.toolButtonPan.setMinimumSize(QtCore.QSize(109, 0))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/mActionPan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPan.setIcon(icon14)
        self.toolButtonPan.setCheckable(True)
        self.toolButtonPan.setChecked(False)
        self.toolButtonPan.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPan.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPan.setObjectName("toolButtonPan")
        self.gridLayout_9.addWidget(self.toolButtonPan, 2, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 1, 3, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_15.addWidget(self.tabWidget)
        self.gridLayout_18.addLayout(self.verticalLayout_15, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "pyArchInit Gestione Scavi - Scheda US", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Dialog", "DBMS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(QtGui.QApplication.translate("Dialog", "Reload DB", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_first_rec.setToolTip(QtGui.QApplication.translate("Dialog", "First rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_prev_rec.setToolTip(QtGui.QApplication.translate("Dialog", "Prev rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_rec.setToolTip(QtGui.QApplication.translate("Dialog", "Next rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_last_rec.setToolTip(QtGui.QApplication.translate("Dialog", "Last rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_rec.setToolTip(QtGui.QApplication.translate("Dialog", "New record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setToolTip(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete.setToolTip(QtGui.QApplication.translate("Dialog", "Delete record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_search.setToolTip(QtGui.QApplication.translate("Dialog", "new search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_go.setToolTip(QtGui.QApplication.translate("Dialog", "search !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_sort.setToolTip(QtGui.QApplication.translate("Dialog", "Order by", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_view_all.setToolTip(QtGui.QApplication.translate("Dialog", "View alls records", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("Dialog", "DB Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("Dialog", "Ordinamento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Dialog", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog", "record n.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_corrente.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Dialog", "record tot.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_tot.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sito.setItemText(0, QtGui.QApplication.translate("Dialog", "Inserisci un valore", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(0, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(1, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(2, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(3, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(4, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(5, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(6, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(7, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(8, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(9, QtGui.QApplication.translate("Dialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(10, QtGui.QApplication.translate("Dialog", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(11, QtGui.QApplication.translate("Dialog", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(12, QtGui.QApplication.translate("Dialog", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(13, QtGui.QApplication.translate("Dialog", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(14, QtGui.QApplication.translate("Dialog", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(15, QtGui.QApplication.translate("Dialog", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(16, QtGui.QApplication.translate("Dialog", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(17, QtGui.QApplication.translate("Dialog", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(18, QtGui.QApplication.translate("Dialog", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_area.setItemText(19, QtGui.QApplication.translate("Dialog", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Sito ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "US", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_strat.setItemText(0, QtGui.QApplication.translate("Dialog", "Taglio", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_strat.setItemText(1, QtGui.QApplication.translate("Dialog", "Strato di terra", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_strat.setItemText(2, QtGui.QApplication.translate("Dialog", "Strato di terra e calce", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_strat.setItemText(3, QtGui.QApplication.translate("Dialog", "Strato di macerie", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_strat.setItemText(4, QtGui.QApplication.translate("Dialog", "Strato di sabbie", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_strat.setItemText(5, QtGui.QApplication.translate("Dialog", "Struttura in muratura", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_strat.setItemText(6, QtGui.QApplication.translate("Dialog", "Riempimento", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(0, QtGui.QApplication.translate("Dialog", "Attivita\' di cantiere", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(1, QtGui.QApplication.translate("Dialog", "Abbandono", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(2, QtGui.QApplication.translate("Dialog", "Fognatura", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(3, QtGui.QApplication.translate("Dialog", "Fondazione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(4, QtGui.QApplication.translate("Dialog", "Fossa da grano", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(5, QtGui.QApplication.translate("Dialog", "Livellamento", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(6, QtGui.QApplication.translate("Dialog", "Muro", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(7, QtGui.QApplication.translate("Dialog", "Pavimentazione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(8, QtGui.QApplication.translate("Dialog", "Pavimentazione a mosaico", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_def_intepret.setItemText(9, QtGui.QApplication.translate("Dialog", "Palo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Definizione stratigrafica", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Definizione Interpretata", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Periodizzazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("Dialog", "Iniziale ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Finale ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Attivita\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "Struttura", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_per_iniz.setItemText(0, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_per_iniz.setItemText(1, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog", "Periodo ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Fase ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Periodo ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Dialog", "Fase ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_metodo.setItemText(0, QtGui.QApplication.translate("Dialog", "Meccanico", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_metodo.setItemText(1, QtGui.QApplication.translate("Dialog", "Stratigrafico", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Dialog", "Metodo di scavo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Anno", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scavato.setItemText(0, QtGui.QApplication.translate("Dialog", " ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scavato.setItemText(1, QtGui.QApplication.translate("Dialog", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scavato.setItemText(2, QtGui.QApplication.translate("Dialog", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Scavato", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Rapporti stratigrafici", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_rapporti.setText(QtGui.QApplication.translate("Dialog", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Tipo di rapporto", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_rapporti.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "US", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Periodizzazione - Rapporti Stratigrafici", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_descrizione.setHtml(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:13pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Descrizione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Interpretazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_formazione.setItemText(0, QtGui.QApplication.translate("Dialog", "Antropico", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_formazione.setItemText(1, QtGui.QApplication.translate("Dialog", "Naturale", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_inclusi.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "                     Inclusi                ", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_campioni.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "                     Campioni                ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Formazione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(0, QtGui.QApplication.translate("Dialog", "Marrone", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(1, QtGui.QApplication.translate("Dialog", "Marrone chiaro", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(2, QtGui.QApplication.translate("Dialog", "Marrone scuro", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(3, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(4, QtGui.QApplication.translate("Dialog", "Giallo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(5, QtGui.QApplication.translate("Dialog", "Giallo scuro", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(6, QtGui.QApplication.translate("Dialog", "Giallo chiaro", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(7, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_colore.setItemText(9, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Colore", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consistenza.setItemText(0, QtGui.QApplication.translate("Dialog", "Argillosa", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consistenza.setItemText(1, QtGui.QApplication.translate("Dialog", "Compatta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consistenza.setItemText(2, QtGui.QApplication.translate("Dialog", "Friabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consistenza.setItemText(3, QtGui.QApplication.translate("Dialog", "Sabbiosa", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consistenza.setItemText(4, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consistenza.setItemText(6, QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog", "Consistenza", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(0, QtGui.QApplication.translate("Dialog", "Insufficiente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(1, QtGui.QApplication.translate("Dialog", "Scarso", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(2, QtGui.QApplication.translate("Dialog", "Buono", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(3, QtGui.QApplication.translate("Dialog", "Discreto", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione.setItemText(4, QtGui.QApplication.translate("Dialog", "Ottimo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_inclusi.setText(QtGui.QApplication.translate("Dialog", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_campioni.setText(QtGui.QApplication.translate("Dialog", "inserisci riga", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "Stato di conservazione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_schedatore.setItemText(0, QtGui.QApplication.translate("Dialog", "Luca Mandolesi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Dialog", "Schedatore", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog", "Data schedatura", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Dati Fisici - Dati Schedatore", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("Dialog", "Visualizzazione GIS", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGis.setShortcut(QtGui.QApplication.translate("Dialog", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("Dialog", "Attivazione Preview pianta US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreview.setText(QtGui.QApplication.translate("Dialog", "Preview pianta US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreview.setShortcut(QtGui.QApplication.translate("Dialog", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("Dialog", "Apri schede US selezionate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showSelectedFeatures.setToolTip(QtGui.QApplication.translate("Dialog", "Show Selcted Features", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showSelectedFeatures.setText(QtGui.QApplication.translate("Dialog", "apri schede US", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("Dialog", "Esporta schede US in formato PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setToolTip(QtGui.QApplication.translate("Dialog", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setText(QtGui.QApplication.translate("Dialog", "export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("Dialog", "GIS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setToolTip(QtGui.QApplication.translate("Dialog", "Pan tool", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setShortcut(QtGui.QApplication.translate("Dialog", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Tools", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
