#!/bin/bash

# For every user in /home/ ...
for HOME_U in /home/*?; do

# Obtain the username
USER=$( basename ${HOME_U} )

# In case the user is active (exists in /etc/shadow) ...
if [ $( grep -c "${USER}:.*:.*:.*:.*:.*:::" /etc/shadow ) == 1 ] \
&& [ $( grep -c "${USER}:.*:.*:.*:.*:.*:/bin/.*sh" /etc/passwd ) == 1 ] \
&& [ -d ${HOME_U}/.config ] \
&& [ -d ${HOME_U} ]; then

# Delete cadtools plugin
rm -R /home/${USER}/.qgis/cadtools/

# Delete pyarchinit plugin
rm -R /home/${USER}/.qgis/pyarchinit/

# Delete VTEnviro plugin
rm -R /home/${USER}/.qgis/VTEnviro/

fi
done
